# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
trust-domain: mobile
task-priority: highest

taskgraph:
  register: firefox_tv_taskgraph:register
  repositories:
    mobile:
      name: "Firefox TV"
  cached-task-prefix: project.mobile.firefox-tv
  decision-parameters: 'firefox_tv_taskgraph:get_decision_parameters'

workers:
  aliases:
    b-android:
      provisioner: aws-provisioner-v1
      implementation: docker-worker
      os: linux
      worker-type: 'mobile-{level}-b-firefox-tv'
    images:
      provisioner: aws-provisioner-v1
      implementation: docker-worker
      os: linux
      worker-type: 'mobile-{level}-images'
    dep-signing:
      provisioner: scriptworker-k8s
      implementation: scriptworker-signing
      os: scriptworker
      worker-type: mobile-t-signing
    signing:
      provisioner: scriptworker-k8s
      implementation: scriptworker-signing
      os: scriptworker
      worker-type:
        by-level:
          "3": mobile-3-signing
          default: mobile-t-signing
    push-apk:
      provisioner: scriptworker-k8s
      implementation: scriptworker-push-apk
      os: scriptworker
      worker-type: 'mobile-{level}-pushapk'

scriptworker:
  scope-prefix: project:mobile:firefox-tv:releng
